import smtplib
import schedule
import time
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

SMTP_SERVER = 'smtp.gmail.com' 
SMTP_PORT = 587
EMAIL_ADDRESS = 'cozmorry@gmail.com'
EMAIL_PASSWORD = 'vxxd squf ykwx flro'
RECIPIENT_EMAIL = 'oneboycozy@gmail.com'

def send_email():
    
    msg = MIMEMultipart()
    msg['From'] = EMAIL_ADDRESS
    msg['To'] = RECIPIENT_EMAIL
    msg['Subject'] = 'Daily Email Sent by your Python script - {}'.format(datetime.now().strftime('%Y-%m-%d'))
    
    body = 'Hello mf. Goodmorning WAKE UP!!!!!!!!!!!. This email has been autogenerated and sent to you by the python script Dev Cozmorry created on 5th July 2024 for sending auto emails on a scheduler. Goodluck and enjoy!!!!'
    msg.attach(MIMEText(body, 'plain'))
    
    try:
        
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
        text = msg.as_string()
        server.sendmail(EMAIL_ADDRESS, RECIPIENT_EMAIL, text)
        server.quit()
        print('Email sent successfully!')
    except Exception as e:
        print(f'Failed to send email: {e}')


schedule.every().day.at("11:00").do(send_email)

print('Scheduler started...')
while True:
    schedule.run_pending()
    time.sleep(1)
